post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjYzZmQxOWZiNjk0NGQ2ZWU2NWI0YTE1MyIsImlhdCI6MTY3NzUzMTg3NCwiZXhwIjoxNjc3NTM1NDc0fQ.ah8QR1fX4jTwMKFV_BqbpJRWZVZJZ_jFbHttSiPsoeM

{
    "title": "Manchester",
    "author": "Arthur",
    "url": "132321323123",
    "likes": 22
}